title: Hello, world! I'm Ankit Rawal
description: >  
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/Blog-jekyll"  
url: ""  
site-twitter:  
 
author: Ankit Rawal  
author-img: ankitrawal.jpg  
about-author: I am a web developer and a competetive programmer. Always hungry to keep learning.  
social-twitter:  
social-facebook: 
social-github:   
social-linkedin:  
social-email:  
 
discus-identifier:   

 
analytics:  
 
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
